// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoList.API.Building.Persistence.Contexts;

#nullable disable

namespace TodoList.API.Building.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoList.API.Building.Todos.Domains.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasItemsToProcess")
                        .HasColumnType("boolean")
                        .HasColumnName("has_items_to_process");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_todo");

                    b.ToTable("todo", (string)null);
                });

            modelBuilder.Entity("TodoList.API.Building.Todos.Domains.Todo", b =>
                {
                    b.OwnsMany("TodoList.API.Building.Todos.Domains.Item", "Items", b1 =>
                        {
                            b1.Property<Guid>("TodoId")
                                .HasColumnType("uuid")
                                .HasColumnName("todo_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("TodoId", "Id")
                                .HasName("pk_item");

                            b1.ToTable("item", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TodoId")
                                .HasConstraintName("fk_item_todos_todo_id");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
